### ISSUE TITLE
nrf firmware question

### ISSUE THREAD

**Issue by pokerfacett** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#11]
hi 
The firmware nRF52_driver_firmware.hex is just adapt nRF52840？I flash the firmware in nRF52832 and it could not work

**Comment by Matheus-Garbelini** [comment]
Hi @pokerfacett nRF52840 is required because it has native USB. 
nRF52832 on the other hand does not support USB natively.

**Comment by pokerfacett** [comment]
OK tks，I will change nRF52840 to retry
