### ISSUE TITLE
Compiling smp_server on Windows

### ISSUE THREAD

**Issue by hubuhubu** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#15]
Hi Matheus, 

When trying to test with non_compliance_dhcheck_skip.py I would need to install BLESMPServer. 

But I'm having trouble compiling the BLESMPServer on Windows machine. stdint.h, sys/uio.h and many more files are missing. 
Do you have a solution ? 
Thanks, 
Hung

**Comment by yogeshkm20** [comment]
Hi Matheus, 
I think my problem is related. Where do I get the install_smp_server.sh ?

Thanks,

**Comment by Matheus-Garbelini** [comment]
Hi @hubuhubu  and @yogeshkm20 the smp_server requires a linux OS due to requirements on some crypto drivers. I recommend using ubuntu 18.04
