### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by williameriksson** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#2]
Hi,
first of all: great work with this research!

When I first tried to run `CC_connection_req_crash.py` I got undefined reference to method `raw`.
I had to import it manually by:
`from scapy.compat import raw`

Does it work straight out of the box for you?

**Comment by Matheus-Garbelini** [comment]
@williameriksson thanks for the feedback. We may have forgotten to add this import after some cleanup. I'll do a commit and let you know.

**Comment by Matheus-Garbelini** [comment]
@williameriksson fixed by 83db7f478a164a2beff6b75f9f315f93b56015c1
