### ISSUE TITLE
Question about LEDs color of NRF dongle flashed in the firware.

### ISSUE THREAD

**Issue by uncletong** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#23]
Hello,

I would like to know what's the meaning of the LEDs color of NRF dongle?

I have trouble when using this firmwire. Sometimes, the NRF dongle's LEDs are both turning to light event I stoped receive of send packets. What's more, after this situation happens for a while, the NRF dongle can't receive or send packets any more.

How can I Position this problem？Could I get some more information about LEDS and LEDS color?

**Comment by Matheus-Garbelini** [comment]
Hi @uncletong 
We have answered this here:
https://github.com/Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks/issues/24#issuecomment-1002426813
