### ISSUE TITLE
NRF52_CMD_CHECKSUM_ERROR

### ISSUE THREAD

**Issue by shuimoshusheng** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#36]
Thank you for your open-source sharing. 
When I use the examples, I always prompt NRF52-CMD-CHECKSUM-ERROR like this：
![image](https://github.com/Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks/assets/15867686/dbdfc06b-c144-4c5d-944d-2e8f614ea0f4)

My Device is nRF52480 MDK USB Dongle，Use this method [uf2boot](https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/programming/uf2boot/#updating-the-application-firmware)  to convert hex to UF2。Then updated firmware。

**Comment by yyh12138** [comment]
I also meet the same question. It seems that the c in raw_receive() is not correctly resolved.

**Comment by cyberxml** [comment]
I was able to successfully program an older nRF52840 MDK.

>UF2 Bootloader 0.2.13-42-g82464f9-dirty lib/nrfx (v2.0.0) lib/tinyusb (legacy-1500-g23df777b) s140 6.1.1
>Model: nRF52840 MDK USB Dongle
>Board-ID: nRF52840-Dongle-v1
>Date: Feb  3 2020

I used the uf2conv tool from the MS github: https://github.com/Microsoft/uf2

`python3 uf2conf.py s140_nrf52_6.1.1_softdevice.hex -c -f 0xADA52840`

And just copied the output (flash.uf2) to the root directory when the MDK was in file mode (hold reset when inserting the usb)

**Comment by shuimoshusheng** [comment]
> I was able to successfully program an older nRF52840 MDK.
> 
> > UF2 Bootloader 0.2.13-42-g82464f9-dirty lib/nrfx (v2.0.0) lib/tinyusb (legacy-1500-g23df777b) s140 6.1.1
> > Model: nRF52840 MDK USB Dongle
> > Board-ID: nRF52840-Dongle-v1
> > Date: Feb  3 2020
> 
> I used the uf2conv tool from the MS github: https://github.com/Microsoft/uf2
> 
> `python3 uf2conf.py s140_nrf52_6.1.1_softdevice.hex -c -f 0xADA52840`
> 
> And just copied the output (flash.uf2) to the root directory when the MDK was in file mode (hold reset when inserting the usb)

Thanks，I will try it.
